on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: statista-oss/find-openAPI-Specifications
      - uses: statista-oss/eventcatalog-feeder-action@main
        with:
          domain: foobar
          domain-slug: foobar
          catalog-repo: PIT-Shared/api-catalog